# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/anantoni/ClionProjects/OS-F14-Prj1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/anantoni/ClionProjects/OS-F14-Prj1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anantoni/ClionProjects/OS-F14-Prj1/CMakeFiles /home/anantoni/ClionProjects/OS-F14-Prj1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anantoni/ClionProjects/OS-F14-Prj1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OS_F14_Prj1

# Build rule for target.
OS_F14_Prj1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OS_F14_Prj1
.PHONY : OS_F14_Prj1

# fast build rule for target.
OS_F14_Prj1/fast:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/build
.PHONY : OS_F14_Prj1/fast

hash/Bucket.o: hash/Bucket.cpp.o
.PHONY : hash/Bucket.o

# target to build an object file
hash/Bucket.cpp.o:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/hash/Bucket.cpp.o
.PHONY : hash/Bucket.cpp.o

hash/Bucket.i: hash/Bucket.cpp.i
.PHONY : hash/Bucket.i

# target to preprocess a source file
hash/Bucket.cpp.i:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/hash/Bucket.cpp.i
.PHONY : hash/Bucket.cpp.i

hash/Bucket.s: hash/Bucket.cpp.s
.PHONY : hash/Bucket.s

# target to generate assembly for a file
hash/Bucket.cpp.s:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/hash/Bucket.cpp.s
.PHONY : hash/Bucket.cpp.s

hash/Hash.o: hash/Hash.cpp.o
.PHONY : hash/Hash.o

# target to build an object file
hash/Hash.cpp.o:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/hash/Hash.cpp.o
.PHONY : hash/Hash.cpp.o

hash/Hash.i: hash/Hash.cpp.i
.PHONY : hash/Hash.i

# target to preprocess a source file
hash/Hash.cpp.i:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/hash/Hash.cpp.i
.PHONY : hash/Hash.cpp.i

hash/Hash.s: hash/Hash.cpp.s
.PHONY : hash/Hash.s

# target to generate assembly for a file
hash/Hash.cpp.s:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/hash/Hash.cpp.s
.PHONY : hash/Hash.cpp.s

inverted_index/InvertedIndexList.o: inverted_index/InvertedIndexList.cpp.o
.PHONY : inverted_index/InvertedIndexList.o

# target to build an object file
inverted_index/InvertedIndexList.cpp.o:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/inverted_index/InvertedIndexList.cpp.o
.PHONY : inverted_index/InvertedIndexList.cpp.o

inverted_index/InvertedIndexList.i: inverted_index/InvertedIndexList.cpp.i
.PHONY : inverted_index/InvertedIndexList.i

# target to preprocess a source file
inverted_index/InvertedIndexList.cpp.i:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/inverted_index/InvertedIndexList.cpp.i
.PHONY : inverted_index/InvertedIndexList.cpp.i

inverted_index/InvertedIndexList.s: inverted_index/InvertedIndexList.cpp.s
.PHONY : inverted_index/InvertedIndexList.s

# target to generate assembly for a file
inverted_index/InvertedIndexList.cpp.s:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/inverted_index/InvertedIndexList.cpp.s
.PHONY : inverted_index/InvertedIndexList.cpp.s

inverted_index/RecordPointer.o: inverted_index/RecordPointer.cpp.o
.PHONY : inverted_index/RecordPointer.o

# target to build an object file
inverted_index/RecordPointer.cpp.o:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/inverted_index/RecordPointer.cpp.o
.PHONY : inverted_index/RecordPointer.cpp.o

inverted_index/RecordPointer.i: inverted_index/RecordPointer.cpp.i
.PHONY : inverted_index/RecordPointer.i

# target to preprocess a source file
inverted_index/RecordPointer.cpp.i:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/inverted_index/RecordPointer.cpp.i
.PHONY : inverted_index/RecordPointer.cpp.i

inverted_index/RecordPointer.s: inverted_index/RecordPointer.cpp.s
.PHONY : inverted_index/RecordPointer.s

# target to generate assembly for a file
inverted_index/RecordPointer.cpp.s:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/inverted_index/RecordPointer.cpp.s
.PHONY : inverted_index/RecordPointer.cpp.s

inverted_index/TownNode.o: inverted_index/TownNode.cpp.o
.PHONY : inverted_index/TownNode.o

# target to build an object file
inverted_index/TownNode.cpp.o:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/inverted_index/TownNode.cpp.o
.PHONY : inverted_index/TownNode.cpp.o

inverted_index/TownNode.i: inverted_index/TownNode.cpp.i
.PHONY : inverted_index/TownNode.i

# target to preprocess a source file
inverted_index/TownNode.cpp.i:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/inverted_index/TownNode.cpp.i
.PHONY : inverted_index/TownNode.cpp.i

inverted_index/TownNode.s: inverted_index/TownNode.cpp.s
.PHONY : inverted_index/TownNode.s

# target to generate assembly for a file
inverted_index/TownNode.cpp.s:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/inverted_index/TownNode.cpp.s
.PHONY : inverted_index/TownNode.cpp.s

inverted_index/Triple.o: inverted_index/Triple.cpp.o
.PHONY : inverted_index/Triple.o

# target to build an object file
inverted_index/Triple.cpp.o:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/inverted_index/Triple.cpp.o
.PHONY : inverted_index/Triple.cpp.o

inverted_index/Triple.i: inverted_index/Triple.cpp.i
.PHONY : inverted_index/Triple.i

# target to preprocess a source file
inverted_index/Triple.cpp.i:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/inverted_index/Triple.cpp.i
.PHONY : inverted_index/Triple.cpp.i

inverted_index/Triple.s: inverted_index/Triple.cpp.s
.PHONY : inverted_index/Triple.s

# target to generate assembly for a file
inverted_index/Triple.cpp.s:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/inverted_index/Triple.cpp.s
.PHONY : inverted_index/Triple.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/main.cpp.s
.PHONY : main.cpp.s

record/Record.o: record/Record.cpp.o
.PHONY : record/Record.o

# target to build an object file
record/Record.cpp.o:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/record/Record.cpp.o
.PHONY : record/Record.cpp.o

record/Record.i: record/Record.cpp.i
.PHONY : record/Record.i

# target to preprocess a source file
record/Record.cpp.i:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/record/Record.cpp.i
.PHONY : record/Record.cpp.i

record/Record.s: record/Record.cpp.s
.PHONY : record/Record.s

# target to generate assembly for a file
record/Record.cpp.s:
	$(MAKE) -f CMakeFiles/OS_F14_Prj1.dir/build.make CMakeFiles/OS_F14_Prj1.dir/record/Record.cpp.s
.PHONY : record/Record.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... OS_F14_Prj1"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hash/Bucket.o"
	@echo "... hash/Bucket.i"
	@echo "... hash/Bucket.s"
	@echo "... hash/Hash.o"
	@echo "... hash/Hash.i"
	@echo "... hash/Hash.s"
	@echo "... inverted_index/InvertedIndexList.o"
	@echo "... inverted_index/InvertedIndexList.i"
	@echo "... inverted_index/InvertedIndexList.s"
	@echo "... inverted_index/RecordPointer.o"
	@echo "... inverted_index/RecordPointer.i"
	@echo "... inverted_index/RecordPointer.s"
	@echo "... inverted_index/TownNode.o"
	@echo "... inverted_index/TownNode.i"
	@echo "... inverted_index/TownNode.s"
	@echo "... inverted_index/Triple.o"
	@echo "... inverted_index/Triple.i"
	@echo "... inverted_index/Triple.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... record/Record.o"
	@echo "... record/Record.i"
	@echo "... record/Record.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

